### ISSUE TITLE
apply and seach 'window_length'

### ISSUE THREAD

**Issue by hiremasa** [hiremasa/B4_research#13]
1. apply window_lengh = 3 * t_dur for top TOI
2. search for t_dur from NASA Exoplanet Archive: https://exoplanetarchive.ipac.caltech.edu/cgi-bin/TblView/nph-tblView?app=ExoTbls&config=PS or TOI.csv

**Comment by jpdeleon** [comment]
Based on our previous discussion, I thought you have been using cosine eversince instead of the default biweight. But now you updated the plots, transits are generally detected better than biweight method it seems.

**Comment by hiremasa** [comment]
@jpdeleon 
Yes, the uploaded image (google slide on the right) were from method=biweight.
I tried 3 different algorithms : cosine, gp sqrt_exp and gp periodic_auto.
When we use gp method, we have to optimize kernel_size.

**Comment by hiremasa** [comment]
I guess something wrong with the official wotan implementation.
I tell you it tomorrow.
